const PremierImages=[
    {
        src:"https://in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/tailgate-et00138770-02-07-2021-02-48-39.jpg",
        alt:"zack",
        title:"Zacl",
        subtitle:"English",
    },
    {
        src:"https://in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/zack-snyder-s-justice-league-et00047164-10-04-2021-03-22-49.jpg",
        alt:"zack",
        title:"Zacl",
        subtitle:"English",
    },
    {
        src:"https://in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/rewind-et00304964-01-07-2021-11-17-38.jpg",
        alt:"zack",
        title:"Zacl",
        subtitle:"Telugu",
    },
    {
        src:"https://in.bmscdn.com/iedb/movies/images/extra/vertical_logo/mobile/thumbnail/xxlarge/proximity-et00302306-13-05-2021-10-06-47.jpg",
        alt:"zack",
        title:"Zacl",
        subtitle:"Telugu",
    },
    {
        src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00137312-evsmpzefqs-portrait.jpg",
        alt:"zack",
        title:"Zacl",
        subtitle:"Hindi",
    },
    {
        src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00310901-zwfvttldbm-portrait.jpg",
        alt:"zack",
        title:"Zacl",
        subtitle:"Telugu",
    },
    {
        src:"https://in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:oi-discovery-catalog@@icons@@premiere-icon.png,ox-322,oy-20/et00077622-yhtrswxwmr-portrait.jpg",
        alt:"zack",
        title:"Zacl",
        subtitle:"Hindi",
    },];

    export default PremierImages;